### ISSUE TITLE
cannot backup config on FreeBSD

### ISSUE THREAD

**Issue by biGdada** [ccrisan/motioneye#1060]
when i press the backup button, nothing happens;
`2018-11-12 19:32:15: [motioneye]    ERROR: backup failed: Command '['tar', 'zc',                                      '.']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/motioneye/config.py", line 1680,                                      in backup
    content = subprocess.check_output(['tar', 'zc', '.'], cwd=settings.CONF_PATH                                     )
  File "/usr/local/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['tar', 'zc', '.']' returned non-zero exit status 1
2018-11-12 19:32:15: [motioneye]    ERROR: failed to create backup file
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1548, in _s                                     tack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1756, in wr                                     apper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/motioneye/handlers.py", line 278,                                      in get
    self.backup()
  File "/usr/local/lib/python2.7/site-packages/motioneye/handlers.py", line 205,                                      in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/motioneye/handlers.py", line 802,                                      in backup
    raise Exception('failed to create backup file')
Exception: failed to create backup file
`

**Comment by biGdada** [comment]
changing 
`content = subprocess.check_output(['tar', 'zc', '.'], cwd=settings.CONF_PATH)`
to 
`content = subprocess.check_output(['tar', 'zcf','-', '.'], cwd=settings.CONF_PATH)`
in config.py, line 1680 fixes the problem for me
