### ISSUE TITLE
Email notification - character mapping must return integer, None or unicode

### ISSUE THREAD

**Issue by Artyum** [ccrisan/motioneye#1124]
Hi and hello to everyone as this is my first post in this project.

I have a clean installation on Raspberry Pi 3+ with Raspbian Stretch. I follow Install-On-Raspbian guide with no problems. Camera, motion detection and most of things seems to work but email notification does not work at all. When I hit Test Email I got:
Notification email failed: character mapping must return integer, None or unicode!

cat syslog:

Jan 20 14:17:45 raspberrypi meyectl[324]: Traceback (most recent call last):
Jan 20 14:17:45 raspberrypi meyectl[324]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/handlers.py", line 885, in test
Jan 20 14:17:45 raspberrypi meyectl[324]:     subject=subject, message=message, files=[])
Jan 20 14:17:45 raspberrypi meyectl[324]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/sendmail.py", line 58, in send_mail
Jan 20 14:17:45 raspberrypi meyectl[324]:     conn.login(account, password)
Jan 20 14:17:45 raspberrypi meyectl[324]:   File "/usr/lib/python2.7/smtplib.py", line 607, in login
Jan 20 14:17:45 raspberrypi meyectl[324]:     (code, resp) = self.docmd(encode_cram_md5(resp, user, password))
Jan 20 14:17:45 raspberrypi meyectl[324]:   File "/usr/lib/python2.7/smtplib.py", line 571, in encode_cram_md5
Jan 20 14:17:45 raspberrypi meyectl[324]:     response = user + " " + hmac.HMAC(password, challenge).hexdigest()
Jan 20 14:17:45 raspberrypi meyectl[324]:   File "/usr/lib/python2.7/hmac.py", line 75, in __init__
Jan 20 14:17:45 raspberrypi meyectl[324]:     self.outer.update(key.translate(trans_5C))
Jan 20 14:17:45 raspberrypi meyectl[324]: TypeError: character mapping must return integer, None or unicode

I found some very old posts on this issue in the internet (like 5-10 years old) but I could not find a working solution. I would gladly help to test the fix for this.

**Comment by Artyum** [comment]
The solutions from https://github.com/ccrisan/motioneyeos/issues/595 don't work :(

**Comment by Artyum** [comment]
I got it working after change in vi /usr/lib/python2.7/smtplib.py at line 594:
```
#preferred_auths = [AUTH_CRAM_MD5, AUTH_PLAIN, AUTH_LOGIN]
preferred_auths = [AUTH_PLAIN, AUTH_CRAM_MD5, AUTH_LOGIN]
```
I hope it will help someone :D

**Comment by hmouridsen** [comment]
> I got it working after change in /usr/lib/python2.7/smtplib.py at line 594:
> 
> ```
> #preferred_auths = [AUTH_CRAM_MD5, AUTH_PLAIN, AUTH_LOGIN]
> preferred_auths = [AUTH_PLAIN, AUTH_CRAM_MD5, AUTH_LOGIN]
> ```
> I hope it will help someone :D

Hi

I’m fighting with the same mail problem.

I have 3 cameras. All of them gives me the same error in email notification - however camera1 is sending the notification. Camera 2 and 3 is not sending notifications?

How can I edit this? I’m running the OS version

Thanks

**Comment by sky-lake** [comment]
Similar to  Voodoofly's comment in [issue 595](https://github.com/ccrisan/motioneyeos/issues/595), I get the "Notification email failed: character mapping must return integer, None or unicode", however, if I hit apply, I get notification e-mails just fine.
