### ISSUE TITLE
unexpected keyword argument 'camera_id'

### ISSUE THREAD

**Issue by lwvining** [ccrisan/motioneye#1128]
I keep getting this error in the motioneye.log 
I am using motioneye on Ubunttu 14.04 on an old netbook with 4 raspberry zeros running motioneyeOS.
also had some problems with saving images back to the netbook after I had it working . I was trying to get faster notifications of motion by keeping them locale. I have it setup to text me when motion is detected, sending images via text because I have hughesnet and cannot do anything external.

heres the last clip of the log file.
2019-01-22 16:10:09: [motioneye]    ERROR: add_timeout() got an unexpected keyword argument 'camera_id'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1115, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1298, in wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/motioneye/handlers.py", line 970, in get
    self.current(camera_id)
  File "/usr/local/lib/python2.7/dist-packages/motioneye/handlers.py", line 205, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/motioneye/handlers.py", line 1033, in current
    camera_id=camera_id, retry=retry + 1)
TypeError: add_timeout() got an unexpected keyword argument 'camera_id'
2019-01-22 16:10:09: [motioneye]    ERROR: 500 GET /picture/1/current/?_=1548195009069&width=0.7&_username=admin&_signature=5ae7fc30cda4f20872e3d148feb5c7df2b1988e7 (192.168.42.172) 8.96ms
I appreciate your help

**Comment by lwvining** [comment]
upgrade as root? another error. I tried upgrading python as well
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/tornado
Storing debug log for failure in /root/.pip/pip.log
[pip.log](https://github.com/ccrisan/motioneye/files/2799230/pip.log)
