### ISSUE TITLE
Cannot install...

### ISSUE THREAD

**Issue by worikgh** [ccrisan/motioneye#1226]
On a raspberry pi zero, 
2018-11-13-raspbian-stretch-lite.img

Using pip or pip2 to install motioneye I get a memory error.  Like https://github.com/ccrisan/motioneye/issues/1225#issue-431016775 

Using `git clone`, `python2.7 ./setup.py build; sudo python2.7 ./setup.py install` apears to work.  But on running `meyectl startserver` get the error:

```
 $ meyectl  startserver
Traceback (most recent call last):
  File "/usr/local/bin/meyectl", line 11, in <module>
    load_entry_point('motioneye==0.40rc5', 'console_scripts', 'meyectl')()
  File "/usr/local/lib/python2.7/dist-packages/motioneye-0.40rc5-py2.7.egg/motioneye/meyectl.py", line 254, in main
    import server
  File "/usr/local/lib/python2.7/dist-packages/motioneye-0.40rc5-py2.7.egg/motioneye/server.py", line 28, in <module>
    from tornado.ioloop import IOLoop
  File "/usr/local/lib/python2.7/dist-packages/tornado-6.0.2-py2.7-linux-armv6l.egg/tornado/ioloop.py", line 67
    def fileno(self) -> int:
                     ^
SyntaxError: invalid syntax
```

**Comment by ccrisan** [comment]
Use tornado < 6 (e.g. `pip2 install tornado==5.1.1`)
