### ISSUE TITLE
web interface doesn't load "No closing quotation"

### ISSUE THREAD

**Issue by dadosch** [ccrisan/motioneye#1399]
Ok, so I'm a bit in a hurry as I'm on the site, but motioneye(os) stopped working after configuring motion notification via email (with special chars like ./#+ etc) and configuring motion mask.

The log says
```
2019-08-06 15:25:35: [motioneye]    ERROR: No closing quotation
Traceback (most recent call last):
  File "usr/lib/python2.7/site-packages/tornado/web.py", line 1548, in _stack_context_handle_exception
  File "usr/lib/python2.7/site-packages/tornado/web.py", line 1756, in wrapper
  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 273, in get
  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 205, in wrapper
  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 660, in list
  File "/usr/lib/python2.7/site-packages/motioneye/config.py", line 1382, in motion_camera_dict_to_ui
  File "usr/lib/python2.7/shlex.py", line 279, in split
  File "usr/lib/python2.7/shlex.py", line 269, in next
  File "usr/lib/python2.7/shlex.py", line 96, in get_token
  File "usr/lib/python2.7/shlex.py", line 172, in read_token
ValueError: No closing quotation
```

**Comment by dadosch** [comment]
`'` is probably the special char which is causing the error

**Comment by zagrim** [comment]
I guess everything passed to `shlex.split()` should be validated against (shell) special chars (at least unescaped ones) so it doesn't choke on them.

Since you were able to pinpoint the setting that caused the issue, I guess you got this worked around and got the application working again?

**Comment by CRImier** [comment]
You can probably use `shlex.quote()` to make the password (and login) shell-safe?

**Comment by dadosch** [comment]
> I guess everything passed to `shlex.split()` should be validated against (shell) special chars (at least unescaped ones) so it doesn't choke on them.
> 
> Since you were able to pinpoint the setting that caused the issue, I guess you got this worked around and got the application working again?

Yes, thanks for asking. I had to use a different mail account with no `'` in the password, since changing this mail password would break many things on my server (noreply account)

Interestingly enough, the test mail got send out successfully (with `'` in the password) if I clicked on the button.
