### ISSUE TITLE
Unable to send notification email 

### ISSUE THREAD

**Issue by Deekee62** [ccrisan/motioneye#1403]
Unfortunately I'm unable to send e-mail notifications, sending email via command line using Msmtp just works like a charm.

MotionEye.log
`
Aug 08 13:01:57 RAS-CAM-BEE meyectl[272]:    ERROR: notification email test failed: Connection unexpectedly closed: timed out
Aug 08 13:01:57 RAS-CAM-BEE meyectl[272]: Traceback (most recent call last):
Aug 08 13:01:57 RAS-CAM-BEE meyectl[272]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/handlers.py", line 827, in test
Aug 08 13:01:57 RAS-CAM-BEE meyectl[272]:     subject=subject, message=message, files=[])
Aug 08 13:01:57 RAS-CAM-BEE meyectl[272]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/sendmail.py", line 53, in send_mail
Aug 08 13:01:57 RAS-CAM-BEE meyectl[272]:     conn = smtplib.SMTP(server, port, timeout=settings.SMTP_TIMEOUT)
Aug 08 13:01:57 RAS-CAM-BEE meyectl[272]:   File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
Aug 08 13:01:57 RAS-CAM-BEE meyectl[272]:     (code, msg) = self.connect(host, port)
Aug 08 13:01:57 RAS-CAM-BEE meyectl[272]:   File "/usr/lib/python2.7/smtplib.py", line 318, in connect
Aug 08 13:01:57 RAS-CAM-BEE meyectl[272]:     (code, msg) = self.getreply()
Aug 08 13:01:57 RAS-CAM-BEE meyectl[272]:   File "/usr/lib/python2.7/smtplib.py", line 366, in getreply
Aug 08 13:01:57 RAS-CAM-BEE meyectl[272]:     + str(e))
Aug 08 13:01:57 RAS-CAM-BEE meyectl[272]: SMTPServerDisconnected: Connection unexpectedly closed: timed out
Aug 08 13:01:57 RAS-CAM-BEE meyectl[272]:    ERROR: mjpg client timed out receiving data for camera 1 on port 8081
`

Many thanks in advance for any hint!

**Comment by Deekee62** [comment]
This issue has been solved!

My ISP uses SSL on port 465 and my command line email client MSMTP works just great using that.

As I was so desperate, so that I startet to play around and just use port 25 and "Bingo" the email notifications work now just fine, the funny part is that my ISP suggest to use port 465.
