### ISSUE TITLE
Motioneye on Fedora 31 (beta)

### ISSUE THREAD

**Issue by spxak1** [ccrisan/motioneye#1474]
I know this is still beta for Fedora, but it's out soon I am testing so that I can set up my server with MotionEye on the newest version.

Lots of problems but I cannot do much as I don't know python.

First I had:
`[root@quaoar bin]# meyectl 
Traceback (most recent call last):
  File "/usr/local/bin/meyectl", line 11, in <module>
    load_entry_point('motioneye==0.41', 'console_scripts', 'meyectl')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/site-packages/motioneye/meyectl.py", line 28, in <module>
    import settings
ModuleNotFoundError: No module named 'settings'`

Which was fixed by another redditor suggesting to replace

`import settings`
to
`import motioneye.settings`
in meyectl.py 

This  allowed meyectl to run and offer the syntax prompt. 

Now when I get this:

`[root@quaoar bin]# /usr/bin/meyectl startserver
Traceback (most recent call last):
  File "/usr/bin/meyectl", line 11, in <module>
    load_entry_point('motioneye==0.41', 'console_scripts', 'meyectl')()
  File "/usr/local/lib/python3.7/site-packages/motioneye/meyectl.py", line 248, in main
    load_settings()
  File "/usr/local/lib/python3.7/site-packages/motioneye/meyectl.py", line 57, in load_settings
    for i in xrange(1, len(sys.argv)):
NameError: name 'xrange' is not defined`

Any help would be appreciated.

Thanks for your hard work. Motioneye is gift to us all. Thank you.

**Comment by ccrisan** [comment]
Please use Python2. Python3 is not yet supported.
