### ISSUE TITLE
Cant start motioneye on Alpine

### ISSUE THREAD

**Issue by JedimasterRDW** [ccrisan/motioneye#1587]
i have installed motioneye on alpine and  everything is installed now but when i run the start motioneye command i get the following errors:

AlpineTest2:/etc/init.d# meyectl startserver -b -c /etc/motioneye/motioneye.conf
Traceback (most recent call last):
  File "/usr/bin/meyectl", line 11, in <module>
    load_entry_point('motioneye==0.42', 'console_scripts', 'meyectl')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/motioneye/meyectl.py", line 28, in <module>
    import settings
ModuleNotFoundError: No module named 'settings'

**Comment by kleini** [comment]
Motioneye does not yet support Python 3 completely. See the `python3` branch for the first steps towards Python 3 support. Within that branch, I am able to start motioneye and add a single network camera. There is a lot of more stuff, that still needs to be fixed for Python 3.
