### ISSUE TITLE
Error when trying to start

### ISSUE THREAD

**Issue by Gutz-Pilz** [ccrisan/motioneye#17]
```
root@pi-server:~# /etc/init.d/motioneye start
Starting motionEye server:Traceback (most recent call last):
  File "/usr/local/bin/meyectl", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: jinja2
 failed!
```

```
root@pi-server:~# pip install --ignore-installed motioneye
Collecting motioneye
  Using cached motioneye-0.27.2-2.tar.gz
Collecting tornado>=3.1 (from motioneye)
  Using cached tornado-4.2.1.tar.gz
Collecting jinja2 (from motioneye)
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting pillow (from motioneye)
  Using cached Pillow-2.9.0.tar.gz
Collecting pycurl (from motioneye)
  Using cached pycurl-7.19.5.1.tar.gz
Collecting backports.ssl-match-hostname (from tornado>=3.1->motioneye)
  Using cached backports.ssl_match_hostname-3.4.0.2.tar.gz
Collecting certifi (from tornado>=3.1->motioneye)
  Using cached certifi-2015.9.6.2-py2.py3-none-any.whl
Collecting MarkupSafe (from jinja2->motioneye)
  Using cached MarkupSafe-0.23.tar.gz
Installing collected packages: backports.ssl-match-hostname, certifi, tornado, MarkupSafe, jinja2, pillow, pycurl, motioneye
  Running setup.py install for backports.ssl-match-hostname
  Running setup.py install for tornado
  Running setup.py install for MarkupSafe
  Running setup.py install for pillow
  Running setup.py install for pycurl
  Running setup.py install for motioneye
Successfully installed MarkupSafe-0.23 backports.ssl-match-hostname-3.4.0.2 certifi-2015.9.6.2 jinja2-2.8 motioneye-0.27.2 pillow-2.9.0 pycurl-7.19.5.1 tornado-4.2.1

```

**Comment by kristofejro** [comment]
I have something similar. Does anyone has idea how to solve the problem?

root@raspberrypi:/home/pi/motioneye# /etc/init.d/motioneye start
[....] Starting motionEye server:Traceback (most recent call last):
  File "/usr/local/bin/meyectl", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: certifi
 failed!

**Comment by ccrisan** [comment]
That should be solved by a "sudo pip install certifi", although I have no idea why it isn't already present on your system. How did you install motionEye?
