### ISSUE TITLE
movie playback not working in browser

### ISSUE THREAD

**Issue by anton-thushara** [ccrisan/motioneye#1750]
motioneye version: 0.42
motion version: 4.2.2

Movie play back in browser is not working. downloading and playing the movies works great.
Also thumbnail for movies is also not working.

ERROR: [Errno 2] No such file or directory
May 15 17:39:56 raspberrypi meyectl[1562]: Traceback (most recent call last):
May 15 17:39:56 raspberrypi meyectl[1562]:   File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1548, in _stack_context_handle_exception
May 15 17:39:56 raspberrypi meyectl[1562]:     raise_exc_info((type, value, traceback))
May 15 17:39:56 raspberrypi meyectl[1562]:   File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1756, in wrapper
May 15 17:39:56 raspberrypi meyectl[1562]:     result = method(self, *args, **kwargs)
May 15 17:39:56 raspberrypi meyectl[1562]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/handlers.py", line 1407, in get
May 15 17:39:56 raspberrypi meyectl[1562]:     self.preview(camera_id, filename)
May 15 17:39:56 raspberrypi meyectl[1562]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/handlers.py", line 205, in wrapper
May 15 17:39:56 raspberrypi meyectl[1562]:     return func(self, *args, **kwargs)
May 15 17:39:56 raspberrypi meyectl[1562]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/handlers.py", line 1472, in preview
May 15 17:39:56 raspberrypi meyectl[1562]:     height=self.get_argument('height', None))
May 15 17:39:56 raspberrypi meyectl[1562]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/mediafiles.py", line 810, in get_media_preview
May 15 17:39:56 raspberrypi meyectl[1562]:     if not make_movie_preview(camera_config, full_path):
May 15 17:39:56 raspberrypi meyectl[1562]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/mediafiles.py", line 329, in make_movie_preview
May 15 17:39:56 raspberrypi meyectl[1562]:     subprocess.check_output(actual_cmd.split(), stderr=subprocess.STDOUT)
May 15 17:39:56 raspberrypi meyectl[1562]:   File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
May 15 17:39:56 raspberrypi meyectl[1562]:     process = Popen(stdout=PIPE, *popenargs, **kwargs)
May 15 17:39:56 raspberrypi meyectl[1562]:   File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
May 15 17:39:56 raspberrypi meyectl[1562]:     errread, errwrite)
May 15 17:39:56 raspberrypi meyectl[1562]:   File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
May 15 17:39:56 raspberrypi meyectl[1562]:     raise child_exception
May 15 17:39:56 raspberrypi meyectl[1562]: OSError: [Errno 2] No such file or directory

**Comment by anton-thushara** [comment]
Found the issue. ffmpeg was not installed properly. installed it again 'sudo apt install ffmpeg'.
it works now.
