### ISSUE TITLE
Telegram notification test: error setting certificate verify locations:\n  CAfile: /etc/pki/tls/certs/ca-bundle.crt

### ISSUE THREAD

**Issue by strasharo** [ccrisan/motioneye#2962]
I'm running Motioneye inside a docker container, brand new deployment and when trying to configure a Telegram notification I set the API token and recipient and when I hit the "Test" button I get the following error:

![image](https://github.com/motioneye-project/motioneye/assets/3337997/0d04cb6d-0553-49c4-adac-7a372ba40bf4)

This is the error inside the container:

```
    INFO: no files
   ERROR: telegram notification test failed: (77, 'error setting certificate verify locations:\n  CAfile: /etc/pki/tls/certs/ca-bundle.crt\n  CApath: none')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/motioneye/handlers/config.py", line 730, in test
    sendtelegram.send_message(
  File "/usr/local/lib/python3.11/dist-packages/motioneye/sendtelegram.py", line 41, in send_message
    c.perform()
pycurl.error: (77, 'error setting certificate verify locations:\n  CAfile: /etc/pki/tls/certs/ca-bundle.crt\n  CApath: none')

```

Looks like the path doesn't exist in the container:

```
root@1586d314a079:/# ls -l /etc/pki
ls: cannot access '/etc/pki': No such file or directory
root@1586d314a079:/# 
```

**Comment by Sapor2010** [comment]
Same here (clean install) on a Pi with Debian GNU/Linux 12 (bookworm)  
motionEye Version | 0.43.1b1
Motion Version | 4.6.0

Look like the default path has been change ? 

i created the folder/path /etc/pki/ssl/certs and copied the ca-certificate.crt from /etc/ssl/certs/ca-certificates.crt  and renamed it to ca-bundle.crt 

thats help for me as a workaround.

**Comment by zagrim** [comment]
I wonder if this is the cause: https://github.com/pycurl/pycurl/issues/834

**Comment by joelis10** [comment]
I've got this issue too, manually copying over and changing name to ca-bundle.crt didn't work

**Comment by MichaIng** [comment]
Jep. this is the `pycurl` bug @zagrim linked. We do not define the CA cert path, this is (falsely) auto-detected by `pycurl`.

To verify and workaround for now:
```sh
sudo python3 -m pip install pycurl=7.45.2
```

**Comment by adrian-agp** [comment]
Could you add exporting a proxy for Telegram notifications?

**Comment by aledv** [comment]
Ok, but when I update the image and restart the container I Have to re-apply the change 😑

**Comment by aledv** [comment]
I solved in this way:

```
volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssl/certs/ca-certificates.crt:/etc/pki/tls/certs/ca-bundle.crt:ro
```
    
Bye

**Comment by zagrim** [comment]
Looking back at the [pycurl issue](https://github.com/pycurl/pycurl/issues/834#issuecomment-2540437754), it seems that it got resolved in the end of last year, and the fix should have been included in 7.45.4 of pycurl.

> This should now be resolved with the 7.45.4 wheels. There is now runtime autodetection of the CA bundle path.

So, in case there are no dependency version conflicts that would prevent that and that version is available for you, a possible workaround (inverting the idea of [pycurl downgrade MichaIng mentioned earlier](https://github.com/motioneye-project/motioneye/issues/2962#issuecomment-2159098415)) might be to upgrade pycurl to version 7.45.4.
