### ISSUE TITLE
thread-x.config file parsing fails if there are comments on the same line as event_gap (possibly others)

### ISSUE THREAD

**Issue by legoadk** [ccrisan/motioneye#321]
given this line in a thread-1.config:

```
event_gap 60 # maybe this is too long
```

motionEye fails to properly interpret that line when the interface is loaded with the error:

```
   ERROR: invalid literal for int() with base 10: '60 # maybe this is too long'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tornado/web.py", line 1425, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/usr/lib/python2.7/site-packages/tornado/web.py", line 1627, in wrapper
    result = method(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/motioneye-0.33.4-py2.7.egg/motioneye/handlers.py", line 227, in get
    self.list()
  File "/usr/lib/python2.7/site-packages/motioneye-0.33.4-py2.7.egg/motioneye/handlers.py", line 166, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/motioneye-0.33.4-py2.7.egg/motioneye/handlers.py", line 648, in list
    ui_config = config.motion_camera_dict_to_ui(local_config)
  File "/usr/lib/python2.7/site-packages/motioneye-0.33.4-py2.7.egg/motioneye/config.py", line 1054, in motion_camera_dict_to_ui
    'event_gap': int(data['event_gap']),
ValueError: invalid literal for int() with base 10: '60 # maybe this is too long'
   ERROR: 500 GET /config/list/?_=1475691711909&_username=xxxxx&_signature=4a25cd6a35ecf2395c5b317758522685bf1701db (xxx.xxx.xxx.xxx) 7.35ms
```

This leads to no cameras being shown in the motionEye interface and the error suggesting to reload.

This doesn't seem to cause `motion` itself any issues, however.

**Comment by ccrisan** [comment]
46a2aace31e43775f907d763b83d79a32b1f7927 fixes the issue. Thanks for reporting it and sorry for the late reply.
