### ISSUE TITLE
failure updating on Raspbian Wheezy

### ISSUE THREAD

**Issue by ektus** [ccrisan/motioneye#341]
active Motioneye: 0.34.1 RC1
update to current version failed:
```

pi@ektusRPi2wheezy1 /usr/local/lib/python2.7/dist-packages/motioneye $ sudo pip install --upgrade motioneye
Downloading/unpacking motioneye from https://pypi.python.org/packages/3d/4d/0542aa055536760d77a70bdbf715df89bf863feb699a0237b47058cb7d34/motioneye-0.34.1.tar.gz#md5=e63357940de96113d8fba0910a616fab
  Downloading motioneye-0.34.1.tar.gz (565Kb): 565Kb downloaded
  Running setup.py egg_info for package motioneye
    
Requirement already up-to-date: tornado>=3.1 in /usr/local/lib/python2.7/dist-packages (from motioneye)
Requirement already up-to-date: jinja2 in /usr/local/lib/python2.7/dist-packages (from motioneye)
Requirement already up-to-date: pillow in /usr/local/lib/python2.7/dist-packages (from motioneye)
Requirement already up-to-date: pycurl in /usr/local/lib/python2.7/dist-packages (from motioneye)
Requirement already up-to-date: backports.ssl-match-hostname in /usr/local/lib/python2.7/dist-packages (from tornado>=3.1->motioneye)
Requirement already up-to-date: singledispatch in /usr/local/lib/python2.7/dist-packages (from tornado>=3.1->motioneye)
Requirement already up-to-date: certifi in /usr/local/lib/python2.7/dist-packages (from tornado>=3.1->motioneye)
Requirement already up-to-date: backports-abc>=0.4 in /usr/local/lib/python2.7/dist-packages (from tornado>=3.1->motioneye)
Requirement already up-to-date: MarkupSafe in /usr/local/lib/python2.7/dist-packages (from jinja2->motioneye)
Requirement already up-to-date: six in /usr/local/lib/python2.7/dist-packages (from singledispatch->tornado>=3.1->motioneye)
Installing collected packages: motioneye
  Found existing installation: motioneye 0.34rc1
    Uninstalling motioneye:
      Successfully uninstalled motioneye
  Running setup.py install for motioneye
    Error [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/motioneye/build/motioneye' while executing command /usr/bin/python -c "import setuptools;__file__='/usr/local/lib/python2.7/dist-packages/motioneye/build/motioneye/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-fWYRdC-record/install-record.txt
  Rolling back uninstall of motioneye
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 250, in run
    requirement_set.install(install_options, global_options)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1133, in install
    requirement.install(install_options, global_options)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 577, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 221, in call_subprocess
    cwd=cwd, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/motioneye/build/motioneye'

Storing complete log in /root/.pip/pip.log
pi@ektusRPi2wheezy1 /usr/local/lib/python2.7/dist-packages/motioneye $ 
```

excerpt from log:
```

Installing collected packages: motioneye

  Found existing installation: motioneye 0.34rc1

    Uninstalling motioneye:

      Removing file or directory /usr/local/bin/meyectl
      Removing file or directory /usr/local/lib/python2.7/dist-packages/motioneye
      Removing file or directory /usr/local/lib/python2.7/dist-packages/motioneye-0.34rc1.egg-info
      Removing file or directory /usr/local/share/motioneye/extra/Dockerfile
      Removing file or directory /usr/local/share/motioneye/extra/docker-compose.yml
      Removing file or directory /usr/local/share/motioneye/extra/dropbox.keys
      Removing file or directory /usr/local/share/motioneye/extra/motioneye-256x256.png
      Removing file or directory /usr/local/share/motioneye/extra/motioneye-64x64.png
      Removing file or directory /usr/local/share/motioneye/extra/motioneye.conf.sample
      Removing file or directory /usr/local/share/motioneye/extra/motioneye.init-debian
      Removing file or directory /usr/local/share/motioneye/extra/motioneye.svg
      Removing file or directory /usr/local/share/motioneye/extra/motioneye.systemd-unit
      Removing file or directory /usr/local/share/motioneye/extra/motioneye.systemd-unit-local
      Successfully uninstalled motioneye

  Running setup.py install for motioneye

    Running command /usr/bin/python -c "import setuptools;__file__='/usr/local/lib/python2.7/dist-packages/motioneye/build/motioneye/setup.py';exec(compile(open(__file__).read().replace('\r\n',$
    Error [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/motioneye/build/motioneye' while executing command /usr/bin/python -c "import setuptools;__file__='/usr/lo$

  Rolling back uninstall of motioneye

  Replacing /usr/local/bin/meyectl
  Replacing /usr/local/lib/python2.7/dist-packages/motioneye
  Replacing /usr/local/lib/python2.7/dist-packages/motioneye-0.34rc1.egg-info
  Replacing /usr/local/share/motioneye/extra/Dockerfile
  Replacing /usr/local/share/motioneye/extra/docker-compose.yml
  Replacing /usr/local/share/motioneye/extra/dropbox.keys
  Replacing /usr/local/share/motioneye/extra/motioneye-256x256.png
  Replacing /usr/local/share/motioneye/extra/motioneye-64x64.png
  Replacing /usr/local/share/motioneye/extra/motioneye.conf.sample
  Replacing /usr/local/share/motioneye/extra/motioneye.init-debian
  Replacing /usr/local/share/motioneye/extra/motioneye.svg
  Replacing /usr/local/share/motioneye/extra/motioneye.systemd-unit
  Replacing /usr/local/share/motioneye/extra/motioneye.systemd-unit-local
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 250, in run
    requirement_set.install(install_options, global_options)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1133, in install
    requirement.install(install_options, global_options)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 577, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 221, in call_subprocess
    cwd=cwd, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/motioneye/build/motioneye'

```

**Comment by ektus** [comment]
Umm... user error. I was inside the install directory in preparation for re-inserting my camera resolutin into utils.py. This prevented a successful uninstall an spawned more errors.  Leving the directory and re-issuing the update command did the trick.
