### ISSUE TITLE
Problem DIGOO rtsp Camera

### ISSUE THREAD

**Issue by aspirtakis** [ccrisan/motioneye#495]
Dear Motion ! i have installed motionEy OS and is working great with some usb cameras on my raspberry pi 2 
On my Try to add RTSP link that works fine on VLC i get HEader Error 
the link  i have on vlc is 
rtsp://admin:224935@192.168.2.104/onvif1 
this works on VLC 
I tried added on motion with no luck and is the 2nd RTSP camera that i cannot ADD 

the log show this 
Traceback (most recent call last):
  File "home/ccrisan/motionpie/output/raspberrypi2/target/usr/lib/python2.7/site-packages/tornado/curl_httpclient.py", line 446, in _curl_header_callback
  File "home/ccrisan/motionpie/output/raspberrypi2/target/usr/lib/python2.7/site-packages/tornado/httputil.py", line 189, in parse_line
ValueError: need more than 1 value to unpack

as i read Mr DAve is included on the OS so 
is there anything i do wrong ?
 i can provide remote access to PI if this Helps

**Comment by carryonrewardless** [comment]
I have my Digoo M1Q setup on MotionEye like rtsp://192.168.2.104/onvif2 (note not onvif1) using your link. From memory the username and pwd were just entered in the fields when setting up. Check your password. Unless you have changed it the default admin pwd is 20160404.
Hope that helps.

**Comment by wouterkabouter77** [comment]
When you add the camera you must choose the option rtsp/udp stream in the checkbox camera. See the screenshot below. 

![digoo camera](https://cloud.githubusercontent.com/assets/26790377/25420823/4b41ed18-2a5a-11e7-8f97-4ca6010bfc3d.JPG)

**Comment by aspirtakis** [comment]
Its working with the above Settings /onvif2 
it works also with onvif1 but the PI crash imidatelly 

thanks ALOT for the help

**Comment by jjpeet** [comment]
Hi @ccrisan I also have the same problem with these cameras.
I have been running them directly into Home Assiatnt for a number of years without a problem; using the FFMPEG component. Also, I’m able to open the cameras using VLC.

If I use the approach mentioned above with MotionEye, sometimes a camera image will appear after about 15-30min and then won’t appear after a restart for the same amount of time or worse.

This is patchy, and works with only some of my Digoo M1Q cameras, and others of the same model/firmware not at all. I have other cameras which come into MotionEye without a problem.

I am running MotionEyeOS on a Pi3 (and also as an add-on within HASSIO on a seperate Pi3).

Is there any way I can get these Digoo cams to run reliably in MotionEye?

Thanks for your work on this project its very impressive...

Thx
James
