### ISSUE TITLE
motioneyestop / startserver

### ISSUE THREAD

**Issue by bmili** [ccrisan/motioneye#577]
I'm newbie to motioneye.  Is configuration a problem? I'didnt change  anything manualy .

Boris

pi@raspberrypi:~ $ ps -ef | grep python
root       444     1  2 19:37 ?        00:01:20 /usr/bin/python /usr/local/bin/meyectl startserver -c /etc/motioneye/motioneye.conf
root       992   444  0 19:37 ?        00:00:00 /usr/bin/python /usr/local/bin/meyectl startserver -c /etc/motioneye/motioneye.conf
pi        2274  1249  0 20:41 pts/0    00:00:00 grep --color=auto python

pi@raspberrypi:~ $ sudo /usr/bin/python /usr/local/bin/meyectl stopserver -c /etc/motioneye/motioneye.conf
server is not running

pi@raspberrypi:~ $ sudo /usr/bin/python /usr/local/bin/meyectl startserver -c /etc/motioneye/motioneye.conf
    INFO: hello! this is motionEye server 0.36
    INFO: cleanup started
    INFO: wsswitch started
    INFO: tasks started
    INFO: mjpg client garbage collector started
Traceback (most recent call last):
  File "/usr/local/bin/meyectl", line 9, in <module>
    load_entry_point('motioneye==0.36', 'console_scripts', 'meyectl')()
  File "/usr/local/lib/python2.7/dist-packages/motioneye/meyectl.py", line 255, in main
    server.main(arg_parser, sys.argv[2:], command[:-6])
  File "/usr/local/lib/python2.7/dist-packages/motioneye/server.py", line 435, in main
    run()
  File "/usr/local/lib/python2.7/dist-packages/motioneye/server.py", line 393, in run
    application.listen(settings.PORT, settings.LISTEN)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1943, in listen
    server.listen(port, address)
  File "/usr/local/lib/python2.7/dist-packages/tornado/tcpserver.py", line 142, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python2.7/dist-packages/tornado/netutil.py", line 197, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

**Comment by ccrisan** [comment]
Somehow you have two running instances of motionEye. Make sure you haven't started it twice.
