### ISSUE TITLE
ERROR libcurl link-time version (7.47.0) is older than compile-time version (7.56.1)

### ISSUE THREAD

**Issue by oembsod** [ccrisan/motioneye#730]
Good evening, after the system upgrade to ARMBIAN 5.31 stable Ubuntu 16.04.3 LTS 3.4.113-sun8 and there were problems ("ARMBIAN 5.25 stable Ubuntu 16.04.2 LTS 4.10.0-sun8i" on this version everything worked well). The motioneye.service process does not start.
my syslog
```

Dec  3 23:09:55 localhost systemd[1]: Started motionEye Server.
Dec  3 23:09:56 localhost systemd[1]: Started Cleanup of Temporary Directories.
Dec  3 23:09:57 localhost meyectl[3089]: Traceback (most recent call last):
Dec  3 23:09:57 localhost meyectl[3089]:   File "/usr/local/bin/meyectl", line 11, in <module>
Dec  3 23:09:57 localhost meyectl[3089]:     load_entry_point('motioneye==0.38', 'console_scripts', 'meyectl')()
Dec  3 23:09:57 localhost meyectl[3089]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/meyectl.py", line 254, in main
Dec  3 23:09:57 localhost meyectl[3089]:     import server
Dec  3 23:09:57 localhost meyectl[3089]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/server.py", line 31, in <module>
Dec  3 23:09:57 localhost meyectl[3089]:     import handlers
Dec  3 23:09:57 localhost meyectl[3089]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/handlers.py", line 30, in <module>
Dec  3 23:09:57 localhost meyectl[3089]:     import config
Dec  3 23:09:57 localhost meyectl[3089]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/config.py", line 37, in <module>
Dec  3 23:09:57 localhost meyectl[3089]:     import uploadservices
Dec  3 23:09:57 localhost meyectl[3089]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/uploadservices.py", line 26, in <module>
Dec  3 23:09:57 localhost meyectl[3089]:     import pycurl
Dec  3 23:09:57 localhost meyectl[3089]:   File "build/bdist.linux-armv7l/egg/pycurl.py", line 7, in <module>
Dec  3 23:09:57 localhost meyectl[3089]:   File "build/bdist.linux-armv7l/egg/pycurl.py", line 6, in __bootstrap__
Dec  3 23:09:57 localhost meyectl[3089]: ImportError: pycurl: libcurl link-time version (7.47.0) is older than compile-time version (7.56.1)
Dec  3 23:09:57 localhost systemd[1]: motioneye.service: Main process exited, code=exited, status=1/FAILURE
Dec  3 23:09:57 localhost systemd[1]: motioneye.service: Unit entered failed state.
Dec  3 23:09:57 localhost systemd[1]: motioneye.service: Failed with result 'exit-code'.

```
All the solutions found did not fit.

> **uninstall pycurl.**
> pip uninstall pycurl
> **export LD_LIBRARY_PATH=<<your homebrew's libcurl path>>**
> export LD_LIBRARY_PATH=/usr/local/opt/curl/lib
> export LIBRARY_PATH=/usr/local/opt/curl/lib 
> **reinstall pycurl**
> easy_install pycurl

Error

```

root@orangepipc:~# export LD_LIBRARY_PATH=/usr/local/opt/curl/lib
root@orangepipc:~#  export LIBRARY_PATH=/usr/local/opt/curl/lib
root@orangepipc:~#  easy_install pycurl
Searching for pycurl
Reading https://pypi.python.org/simple/pycurl/
Downloading https://pypi.python.org/packages/12/3f/557356b60d8e59a1cce62ffc07ecc03e4f8a202c86adae34d895826281fb/pycurl-7.43.0.tar.gz#md5=c94bdba01da6004fa38325e9bd6b9760
Best match: pycurl 7.43.0
Processing pycurl-7.43.0.tar.gz
Writing /tmp/easy_install-z35Fe_/pycurl-7.43.0/setup.cfg
Running pycurl-7.43.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-z35Fe_/pycurl-7.43.0/egg-dist-tmp-8h649J
Using curl-config (libcurl 7.56.1)
warning: no files found matching 'src/Makefile'
src/module.c: In function ‘initpycurl’:
src/module.c:424:60: warning: macro "__DATE__" might prevent reproducible builds [-Wdate-time]
     insstr_modinit(d, "COMPILE_DATE", __DATE__ " " __TIME__);
                                                            ^
src/module.c:424:60: warning: macro "__TIME__" might prevent reproducible builds [-Wdate-time]
zip_safe flag not set; analyzing archive contents...
Moving pycurl-7.43.0-py2.7-linux-armv7l.egg to /usr/local/lib/python2.7/dist-packages
Adding pycurl 7.43.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/pycurl-7.43.0-py2.7-linux-armv7l.egg
Processing dependencies for pycurl
Finished processing dependencies for pycurl
```

**Comment by ccrisan** [comment]
This is not a motionEye issue, but rather something to do with the OS and pycurl. There's nothing motionEye can do about that.
