### ISSUE TITLE
Jessie to Stretch Upgrade, pip install motioneye fails due to lack of zlib headers

### ISSUE THREAD

**Issue by jonatversprite** [ccrisan/motioneye#747]
Documenting in case others encounter this error.  Following the instructions https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian and received an error when installing motioneye. I had to install some zlib packages to make it work. I added several packages, so I'm not sure which exact one fixed it.

`pi@raspberrypi:~ $ pip install motioneye
Collecting motioneye
  Downloading motioneye-0.38.tar.gz (756kB)
    100% |████████████████████████████████| 757kB 230kB/s 
Collecting jinja2 (from motioneye)
  Downloading Jinja2-2.10-py2.py3-none-any.whl (126kB)
    100% |████████████████████████████████| 133kB 728kB/s 
Collecting pillow (from motioneye)
  Downloading Pillow-4.3.0.tar.gz (13.9MB)
    100% |████████████████████████████████| 13.9MB 9.9kB/s 
Collecting pycurl (from motioneye)
  Downloading pycurl-7.43.0.1.tar.gz (195kB)
    100% |████████████████████████████████| 204kB 872kB/s 
Collecting tornado>=3.1 (from motioneye)
  Downloading tornado-4.5.2.tar.gz (483kB)
    100% |████████████████████████████████| 491kB 257kB/s 
Collecting MarkupSafe>=0.23 (from jinja2->motioneye)
  Downloading MarkupSafe-1.0.tar.gz
Collecting olefile (from pillow->motioneye)
  Downloading olefile-0.44.zip (74kB)
    100% |████████████████████████████████| 81kB 1.8MB/s 
Collecting backports_abc>=0.4 (from tornado>=3.1->motioneye)
  Downloading backports_abc-0.5-py2.py3-none-any.whl
Collecting certifi (from tornado>=3.1->motioneye)
  Downloading certifi-2017.11.5-py2.py3-none-any.whl (330kB)
    100% |████████████████████████████████| 337kB 358kB/s 
Collecting singledispatch (from tornado>=3.1->motioneye)
  Downloading singledispatch-3.4.0.3-py2.py3-none-any.whl
Collecting six (from singledispatch->tornado>=3.1->motioneye)
  Downloading six-1.11.0-py2.py3-none-any.whl
Building wheels for collected packages: motioneye, pillow, pycurl, tornado, MarkupSafe, olefile
  Running setup.py bdist_wheel for motioneye ... done
  Stored in directory: /home/pi/.cache/pip/wheels/2e/68/14/d669357ec459318c3c84b3d5a5950bc8f6458ae380bac228e5
  Running setup.py bdist_wheel for pillow ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-raRs7i/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpLBE28epip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-2.7
  creating build/lib.linux-armv7l-2.7/PIL
  copying PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/_util.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageCms.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/CurImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/version.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageMath.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageMorph.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/OleFileIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/TarIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageDraw2.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageDraw.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GimpGradientFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImagePalette.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/MspImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PyAccess.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/_binary.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/TiffTags.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/SunImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PSDraw.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FliImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/features.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageWin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageStat.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ContainerIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ExifTags.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageTransform.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/_tkinter_finder.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageGrab.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/__init__.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/WalImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageMode.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GifImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PcfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageFilter.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageChops.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GdImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/MicImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/JpegPresets.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/Image.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageEnhance.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageShow.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageQt.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageOps.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImagePath.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageSequence.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PngImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageFont.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/BdfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageColor.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageTk.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  running egg_info
  writing requirements to Pillow.egg-info/requires.txt
  writing Pillow.egg-info/PKG-INFO
  writing top-level names to Pillow.egg-info/top_level.txt
  writing dependency_links to Pillow.egg-info/dependency_links.txt
  reading manifest file 'Pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.sh'
  no previously-included directories found matching 'docs/_static'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching 'codecov.yml'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.landscape.yaml'
  warning: no previously-included files found matching '.travis'
  warning: no previously-included files found matching '.travis/*'
  warning: no previously-included files found matching 'appveyor.yml'
  warning: no previously-included files found matching 'build_children.sh'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  writing manifest file 'Pillow.egg-info/SOURCES.txt'
  running build_ext
  
  
  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-raRs7i/pillow/setup.py", line 799, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:
  
  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  
  
  ----------------------------------------
  Failed building wheel for pillow
  Running setup.py clean for pillow
  Running setup.py bdist_wheel for pycurl ... done
  Stored in directory: /home/pi/.cache/pip/wheels/a5/5b/c8/f80900b09b49815e1f90dbae2f57e49b3f4c61071db40fb238
  Running setup.py bdist_wheel for tornado ... done
  Stored in directory: /home/pi/.cache/pip/wheels/b3/47/3a/96e12476829cb196adabc879fedb72f1bb2c8613b6961e78e7
  Running setup.py bdist_wheel for MarkupSafe ... done
  Stored in directory: /home/pi/.cache/pip/wheels/88/a7/30/e39a54a87bcbe25308fa3ca64e8ddc75d9b3e5afa21ee32d57
  Running setup.py bdist_wheel for olefile ... done
  Stored in directory: /home/pi/.cache/pip/wheels/20/58/49/cc7bd00345397059149a10b0259ef38b867935ea2ecff99a9b
Successfully built motioneye pycurl tornado MarkupSafe olefile
Failed to build pillow
Installing collected packages: MarkupSafe, jinja2, olefile, pillow, pycurl, backports-abc, certifi, six, singledispatch, tornado, motioneye
  Running setup.py install for pillow ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-raRs7i/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-W4IGzw-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-2.7
    creating build/lib.linux-armv7l-2.7/PIL
    copying PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/_util.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageCms.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/CurImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/version.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageMath.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageMorph.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/OleFileIO.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/TarIO.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageDraw2.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageDraw.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GimpGradientFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImagePalette.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/MspImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PyAccess.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/_binary.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/FontFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/TiffTags.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/SunImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PSDraw.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/FliImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/features.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageWin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageStat.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ContainerIO.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ExifTags.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageTransform.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/_tkinter_finder.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageGrab.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/__init__.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/WalImageFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageMode.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GifImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PcfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageFilter.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageChops.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GdImageFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/MicImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/JpegPresets.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/Image.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageEnhance.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageShow.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageQt.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageOps.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImagePath.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageSequence.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PngImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageFont.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/BdfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageColor.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageTk.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    running egg_info
    writing requirements to Pillow.egg-info/requires.txt
    writing Pillow.egg-info/PKG-INFO
    writing top-level names to Pillow.egg-info/top_level.txt
    writing dependency_links to Pillow.egg-info/dependency_links.txt
    reading manifest file 'Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.travis'
    warning: no previously-included files found matching '.travis/*'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'Pillow.egg-info/SOURCES.txt'
    running build_ext
    
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-raRs7i/pillow/setup.py", line 799, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-raRs7i/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-W4IGzw-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-raRs7i/pillow/

pi@raspberrypi:~ $ sudo apt-get install zlibc zlib-gst zlib1g-dev
...
pi@raspberrypi:~ $ pip install motioneye
Collecting motioneye
Collecting jinja2 (from motioneye)
  Using cached Jinja2-2.10-py2.py3-none-any.whl
Collecting tornado>=3.1 (from motioneye)
Collecting pillow (from motioneye)
  Using cached Pillow-4.3.0.tar.gz
Collecting pycurl (from motioneye)
Collecting MarkupSafe>=0.23 (from jinja2->motioneye)
Collecting singledispatch (from tornado>=3.1->motioneye)
  Using cached singledispatch-3.4.0.3-py2.py3-none-any.whl
Collecting certifi (from tornado>=3.1->motioneye)
  Using cached certifi-2017.11.5-py2.py3-none-any.whl
Collecting backports-abc>=0.4 (from tornado>=3.1->motioneye)
  Using cached backports_abc-0.5-py2.py3-none-any.whl
Collecting olefile (from pillow->motioneye)
Collecting six (from singledispatch->tornado>=3.1->motioneye)
  Using cached six-1.11.0-py2.py3-none-any.whl
Building wheels for collected packages: pillow
  Running setup.py bdist_wheel for pillow ... done
  Stored in directory: /home/pi/.cache/pip/wheels/49/97/22/638a2ad41d85bc151da7c987ae644da429a23e95733fabfd76
Successfully built pillow
Installing collected packages: MarkupSafe, jinja2, six, singledispatch, certifi, backports-abc, tornado, olefile, pillow, pycurl, motioneye
Successfully installed MarkupSafe-1.0 backports-abc-0.5 certifi-2017.11.5 jinja2-2.10 motioneye-0.38 olefile-0.44 pillow-4.3.0 pycurl-7.43.0.1 singledispatch-3.4.0.3 six-1.11.0 tornado-4.5.2
`

**Comment by NikonD7200** [comment]
i think you may have to use sudo : 

"pip install motioneye"
