### ISSUE TITLE
ImportError: No module named motioneye.meyectl

### ISSUE THREAD

**Issue by pirata01** [ccrisan/motioneye#882]
Hi

After performing the following:
```
sudo apt-get install python-pip python-dev curl libssl-dev libcurl4-openssl-dev libjpeg-dev
sudo apt-get install motion
sudo mkdir -p /etc/motioneye
sudo cp /usr/local/share/motioneye/extra/motioneye.conf.sample /etc/motioneye/motioneye.conf
sudo mkdir -p /var/lib/motioneye
sudo cp /usr/local/share/motioneye/extra/motioneye.systemd-unit-local /etc/systemd/system/motioneye.service
sudo systemctl daemon-reload
sudo systemctl enable motioneye
sudo systemctl start motioneye
```

I am using Raspbain - lite and am not able to start the service.

The log file below was extracted using this command.
`journalctl -u motioneye > ~/motioneye.log `

and get the following log entries:
*I'll keep digging around, but any help would be appreciated.

-- Logs begin at Sun 2018-05-20 10:55:58 EDT, end at Sun 2018-05-20 11:36:04 EDT. --
May 20 11:13:24 raspberrypi systemd[1]: Started motionEye Server.
May 20 11:13:26 raspberrypi meyectl[228]: Traceback (most recent call last):
May 20 11:13:26 raspberrypi meyectl[228]:   File "/usr/local/bin/meyectl", line 7, in <module>
May 20 11:13:26 raspberrypi meyectl[228]:     from motioneye.meyectl import main
May 20 11:13:26 raspberrypi meyectl[228]: ImportError: No module named motioneye.meyectl
May 20 11:13:26 raspberrypi systemd[1]: motioneye.service: Main process exited, code=exited, status=1/FAILURE
May 20 11:13:26 raspberrypi systemd[1]: motioneye.service: Unit entered failed state.
May 20 11:13:26 raspberrypi systemd[1]: motioneye.service: Failed with result 'exit-code'.
May 20 11:23:04 raspberrypi systemd[1]: Started motionEye Server.
May 20 11:23:05 raspberrypi meyectl[525]: Traceback (most recent call last):
May 20 11:23:05 raspberrypi meyectl[525]:   File "/usr/local/bin/meyectl", line 7, in <module>
May 20 11:23:05 raspberrypi meyectl[525]:     from motioneye.meyectl import main
May 20 11:23:05 raspberrypi meyectl[525]: ImportError: No module named motioneye.meyectl
May 20 11:23:05 raspberrypi systemd[1]: motioneye.service: Main process exited, code=exited, status=1/FAILURE
May 20 11:23:05 raspberrypi systemd[1]: motioneye.service: Unit entered failed state.
May 20 11:23:05 raspberrypi systemd[1]: motioneye.service: Failed with result 'exit-code'.

**Comment by pirata01** [comment]
I am using the following python version (I read here that 3.0 was not supported)
[https://github.com/ccrisan/motioneye/issues/57](url)
```
import sys
print (sys.version)
```
2.7.13 (default, Nov 24 2017, 17:33:09)

**Comment by pirata01** [comment]
Some progress.  I'm able to start the service with the following command line at the terminal window (using ssh).
` sudo python /usr/local/bin/meyectl startserver -c /etc/motioneye/motioneye.conf`

Looks like a service issues at this point when trying to run the service using:
`sudo systemctl daemon-reload`
`sudo systemctl enable motioneye `
`sudo systemctl start motioneye`

**Comment by pirata01** [comment]
This thread can be closed.
I re-imaged a clean OS install and followed the recommended step and all good.
There may have been older dependencies that caused issues from the get-go.
